baseURL = "https://bernardoespinoza02.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "La Bitácora de Viaje de Bernardo Espinoza "
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu instagram 👇
  twitter_handle = "@ben.espinoza.02"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
